### PR TITLE
Swift 2.0 support

### PR DESCRIPTION
**Pull request by rpowelll**
This pull request adds support for Swift 2 and Xcode 7. So far I've only converted the main framework over to the newer syntax through Xcode's conversion tools, so a fair amount of work still needs to be done.

### CODE REVIEW

**Comment by Pasta** [comment]
Any news on this?

**Comment by phimage** [comment]
This is a Work In Progress Pull Request

See issue #82 and mwermuth fork

**Comment by rpowelll** [comment]
Yeah I'm inclined to close this PR and point people towards @mwermuth's fork.

**Comment by BilalBudhani** [comment]
We're very close to iOS 9 launch date, any timeline on this?

**Comment by phimage** [comment]
@BilalBudhani ask question in issue #82 
and read previous comments before asking here

**Comment by phimage** [comment]
PR can be closed now: 6e7b674a65348b57dc8b98ffeff523bd08f03222

**Pull request closed without merging**
