### PR TITLE
Closes Issue #140 and #142.

### PR DESCRIPTION
**Pull request by pculligan**
Added decoding the URL-encoded `oauth_token_secret` to the OAuth1 flow (in Step 1 and Step 3) so that it would complete. Previous escaped values were preventing proper OAuth signatures.

### CODE REVIEW

**Comment by phimage** [comment]
Thanks for the PR
There is now conflict on makeRequest, can you merge dongri master into your own master to resolve the conflict
`method`(String) become `method.rawValue`(enum)

**Comment by pculligan** [comment]
Changes merged, committed, pushed. New to GitHub flow - let me know if I've missed anything.

**Comment by phimage** [comment]
Just in case, I remove query string using `NSUrlComponent`and remove some unwrap `!` but not tested (I will when I can unit tests)
fdfb368ed2357354a0a16b347e03c829647bbb22

**Comment by phimage** [comment]
Previous comment tested, Unit test added

I revert some change here due to my comprehension of the code after study #80
`OAuthSwiftHTTPRequest` take the previous value, not the combined ones because when doing a POST, `parameters` is not in url query string but in HTTP Body

So the is also a bug in signature when doing a `POST`, because parameters must not be into signature calculation as I understand, and more bugs on the internal use of the post function(if no additional parameters, no body encoded...)...

**Pull request merged**
