### PR TITLE
Adding Slack example to the OAuthDemo

### PR DESCRIPTION
**Pull request by shrutic**
Added Slack OAuth2 example to the demo and updated the README.md file

### CODE REVIEW

**Comment by phimage** [comment]
osx demo must also be completed, code not factorized for the moment ;(

**Comment by shrutic** [comment]
Added Slack OSX Demo as well as requested

**Comment by dongri** [comment]
Thank you! @shrutic @phimage

**Comment by shrutic** [comment]
Thanks Dongri Jin

**Pull request merged**
